name: Update Economic Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install requests
        run: |
          pip install requests

      - name: Download economic calendar
        run: |
          python news.py

      - name: Save calendar
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add economic_calendar.json

          git diff --cached --quiet || git commit -m "Update economic calendar"

          git push
